#!/usr/bin/env ruby

require 'yaml'
require 'json'

CONFIG = YAML.load_file(ARGV.first)
GITHUB_USER, GITHUB_TOKEN, OWNER, REPO, WEBHOOK_URL, NAME_SUFFIX, ICONS, MESSAGE_FORMAT_EMPTY, MESSAGE_FORMAT_EXIST =
  CONFIG.values_at("GITHUB_USER", "GITHUB_TOKEN", "OWNER", "REPO", "WEBHOOK_URL", "NAME_SUFFIX", "ICONS", "MESSAGE_FORMAT_EMPTY", "MESSAGE_FORMAT_EXIST")

def pulls
  JSON.parse(`curl -s -u "#{GITHUB_USER}:#{GITHUB_TOKEN}" https://api.github.com/repos/#{OWNER}/#{REPO}/pulls&state=open`)
end

def reactions(number)
  JSON.parse(`curl -s -u "#{GITHUB_USER}:#{GITHUB_TOKEN}" -H "Accept: application/vnd.github.squirrel-girl-preview" https://api.github.com/repos/#{OWNER}/#{REPO}/issues/#{number}/reactions`)
end

def labels(number)
  JSON.parse(`curl -s -u "#{GITHUB_USER}:#{GITHUB_TOKEN}" https://api.github.com/repos/#{OWNER}/#{REPO}/issues/#{number}/labels`)
end

def to_emoji(reaction)
  case reaction
  when "laugh"
    "smile"
  when "hooray"
    "tada"
  else
    reaction
  end
end

def escape_json_text(text)
  text.gsub('"', '\"')
end

def post(text, options = {}) 
  query = options.merge(text: escape_json_text(text)).map{|k, v| %("#{k}":"#{v}")}.join(",")

  puts      %(curl -s -H "Content-Type: application/json" -X POST -d '{#{query}}' <WEBHOOK_URL>)
  if WEBHOOK_URL
    command = %(curl -s -H "Content-Type: application/json" -X POST -d '{#{query}}' #{WEBHOOK_URL})
    system command
  end
end

messages = pulls.map do |pull|
  number, title, html_url, user = pull["number"], pull["title"], pull["html_url"], pull["user"]["login"]
  states = labels(number).map{|label| "`#{label["name"]}`"}.join(" ")
  marks = reactions(number).map{|reaction| ":#{to_emoji(reaction["content"])}:(#{reaction["user"]["login"]})"}.join(", ")

  [
    %(> *#{title}* #{states}),
    %(> #{html_url}),
    %(> ),
    %(> owner: #{user}),
    %(> reactions: [#{marks}]),
  ].join('\n')
end

p messages
p WEBHOOK_URL: WEBHOOK_URL

format = if messages.empty?
           MESSAGE_FORMAT_EMPTY
         else
           MESSAGE_FORMAT_EXIST
         end
name, icon = ICONS.sample

text = [
  sprintf(format, count: messages.size),
  *messages,
].join('\n\n')

post(text, username: name, icon_url: icon)

