#!/usr/bin/env ruby

require 'yaml'
require 'json'

CONFIG = YAML.load_file(ARGV.first)
GITHUB_USER, GITHUB_TOKEN, OWNER, REPO, WEBHOOK_URL = CONFIG.values_at("GITHUB_USER", "GITHUB_TOKEN", "OWNER", "REPO", "WEBHOOK_URL")

def pulls
  JSON.parse(`curl -s -u "#{GITHUB_USER}:#{GITHUB_TOKEN}" https://api.github.com/repos/#{OWNER}/#{REPO}/pulls&state=open`)
end

def reactions(number)
  JSON.parse(`curl -s -u "#{GITHUB_USER}:#{GITHUB_TOKEN}" -H "Accept: application/vnd.github.squirrel-girl-preview" https://api.github.com/repos/#{OWNER}/#{REPO}/issues/#{number}/reactions`)
end

def labels(number)
  JSON.parse(`curl -s -u "#{GITHUB_USER}:#{GITHUB_TOKEN}" https://api.github.com/repos/#{OWNER}/#{REPO}/issues/#{number}/labels`)
end

def to_emoji(reaction)
  case reaction
  when "laugh"
    "smile"
  when "hooray"
    "tada"
  else
    reaction
  end
end

def image_url(key)
  %w[
    http://3.bp.blogspot.com/-f7RP4FBbHHs/WKbKWONd1UI/AAAAAAABB0Y/xIurZIPrtPgV7X-yDbavc4v98DcYZ8onQCLcB/s800/character_computer_screen_hakase.png
    http://2.bp.blogspot.com/-wg1XBbsYtQ4/U1T3p1v7o3I/AAAAAAAAfUg/A8XE8Wj1ahA/s800/figure_happy.png
    http://1.bp.blogspot.com/-PNcKwFw1PpM/U1T3oDIr9CI/AAAAAAAAfT4/gEn86X8Ppx0/s800/figure_goodjob.png
    http://4.bp.blogspot.com/-WOvX4GkiSEo/U1T3wVr3ovI/AAAAAAAAfWg/RpbQYAHDo2Y/s800/figure_shock.png
  ].find{|url| url.include?(key)}
end

def post(text, options = {}) 
  query = options.merge(text: text).map{|k, v| %("#{k}":"#{v}")}.join(",")

  `curl -s -H "Content-Type: application/json" -X POST -d '{#{query}}' #{WEBHOOK_URL}`
end

messages = pulls.map do |pull|
  number, title, html_url, user = pull["number"], pull["title"], pull["html_url"], pull["user"]["login"]
  states = labels(number).map{|label| "`#{label["name"]}`"}.join(" ")
  marks = reactions(number).map{|reaction| ":#{to_emoji(reaction["content"])}:(#{reaction["user"]["login"]})"}.join(", ")

  [
    %(> *#{title}* #{states}),
    %(> #{html_url}),
    %(> ),
    %(> owner: #{user}),
    %(> reactions: [#{marks}]),
  ].join('\n')
end

p messages

if messages.empty?
  post("今出ているPull Requestはありません。", username: 'プルリク君', icon_url: image_url('figure_happy'))
else
  text = [
    "#{messages.size}件のPull Requestが出ています。",
    *messages,
  ].join('\n\n')

  post(text, username: 'プルリク君', icon_url: image_url('figure_shock'))
end

